### ISSUE TITLE
Only show available hardware-based options in the ui

### ISSUE THREAD

**Issue by TheRealKasumi** [TheRealKasumi/TesLight#109]
With #107 we add a new endpoint that allowed to query advanced information about teslights software and hardware. This especially includes optional hardware, that can be connected to the controller. The UI should only show hardware-based options when the required hardware is available. So for example when the MPU6050 is missing, there should be no motion based effects selectable.

- [x] Implement in frontend

**Comment by danielbayerlein** [comment]
@TheRealKasumi Can you please describe each option?

**Comment by TheRealKasumi** [comment]
Its relatively simple. When you query the new `/api/info/system` endpoint, you will receive a response like this:

```
{
    "socInfo": {...},
    "hardwareInfo": {
        "hwVersion": "2.1",
        "regulatorCount": 2,
        "regulatorVoltage": 5,
        "regulatorCurrentLimit": 6,
        "regulatorCurrentDraw": 0.056253076,
        "regulatorPowerLimit": 24,
        "regulatorPowerDraw": 0.281265378,
        "regulatorTemperature": 70,
        "fanSpeed": 255,
        "mpu6050": 1,
        "ds18b20": 0,
        "bh1750": 0,
        "audioUnit": 0
    },
    "tlSystemInfo": {...}
}
```

Most of this is just nice to have information that we can display in the expert mode later. However the last 4 properties are interesting for you. They tell you how many sensors of a specific type are connected. So if the mpu6050 is `>0`, this means you can display all settings that use the motion sensor. These are the  motion based animations and the "power mode" with the mpu6050. 

Same applies for the bh1750 which is the light sensor. The one that can actually measure the enviornment brightness. If this one is not connected, we should not have it available in the ui as "power mode". 

The audio unit is not relevant yet but is coming very soon. 

ds18b20 tells you how many temperature sensors are connected. This might be interesting to maybe show a warning when the automatic fan mode is selected (#114). When its not available the fan speed will be always at 100% when automatic is selected. 

Does that help?
