### ISSUE TITLE
Highlight contributors

### ISSUE THREAD

**Issue by TheRealKasumi** [TheRealKasumi/TesLight#132]
I think all contributors investing their time, work and money into this project should be highlightes somewhere to thank them. Maybe the readme would be a good playe for that. 

- [x] Find a good way to achieve this
- [x] Discuss with the others

**Comment by danielbayerlein** [comment]
Have a look at https://github.com/all-contributors/all-contributors

**Comment by JakobLichterfeld** [comment]
- [ ] [Install the AllContributors GitHub App](https://github.com/apps/allcontributors/installations/new) --> @TheRealKasumi 
- [ ] Add table template into README.md, see below:
- [ ] Comment on Issue or Pull Request, asking @all-contributors to add a contributor: "@all-contributors please add @<username> for <contributions>" (<contribution>: See the [Emoji Key (Contribution Types Reference)](https://allcontributors.org/docs/en/emoji-key) for a list of valid contribution types.)
- [ ] Status Badge ```[![All Contributors](https://img.shields.io/github/all-contributors/TheRealKasumi/TesLight?color=informational&style=flat-square)](#contributors)```

table template:
```markdown
## Contributors

<!-- ALL-CONTRIBUTORS-LIST:START - Do not remove or modify this section -->
<!-- prettier-ignore-start -->
<!-- markdownlint-disable -->

<!-- markdownlint-restore -->
<!-- prettier-ignore-end -->

<!-- ALL-CONTRIBUTORS-LIST:END -->
```

**Comment by JakobLichterfeld** [comment]
First version, please add what I missed:

@all-contributors please add @TheRealKasumi for bug
@all-contributors please add @TheRealKasumi for code
@all-contributors please add @TheRealKasumi for content
@all-contributors please add @TheRealKasumi for doc
@all-contributors please add @TheRealKasumi for design
@all-contributors please add @TheRealKasumi for example
@all-contributors please add @TheRealKasumi for ideas
@all-contributors please add @TheRealKasumi for infra
@all-contributors please add @TheRealKasumi for maintenance
@all-contributors please add @TheRealKasumi for mentoring
@all-contributors please add @TheRealKasumi for platform
@all-contributors please add @TheRealKasumi for plugin
@all-contributors please add @TheRealKasumi for projectManagement
@all-contributors please add @TheRealKasumi for promotion
@all-contributors please add @TheRealKasumi for question
@all-contributors please add @TheRealKasumi for research
@all-contributors please add @TheRealKasumi for review
@all-contributors please add @TheRealKasumi for security
@all-contributors please add @TheRealKasumi for tool
@all-contributors please add @TheRealKasumi for test
@all-contributors please add @TheRealKasumi for tutorial
@all-contributors please add @TheRealKasumi for video

@all-contributors please add @danielbayerlein for bug
@all-contributors please add @danielbayerlein for code
@all-contributors please add @danielbayerlein for design
@all-contributors please add @danielbayerlein for ideas
@all-contributors please add @danielbayerlein for infra
@all-contributors please add @danielbayerlein for maintenance
@all-contributors please add @danielbayerlein for projectManagement
@all-contributors please add @danielbayerlein for question
@all-contributors please add @danielbayerlein for review
@all-contributors please add @danielbayerlein for translation
@all-contributors please add @danielbayerlein for test

@all-contributors please add @JakobLichterfeld for bug
@all-contributors please add @JakobLichterfeld for code
@all-contributors please add @JakobLichterfeld for doc
@all-contributors please add @JakobLichterfeld for ideas
@all-contributors please add @JakobLichterfeld for infra
@all-contributors please add @JakobLichterfeld for maintenance
@all-contributors please add @JakobLichterfeld for mentoring
@all-contributors please add @JakobLichterfeld for projectManagement
@all-contributors please add @JakobLichterfeld for question
@all-contributors please add @JakobLichterfeld for review
@all-contributors please add @JakobLichterfeld for test
@all-contributors please add @JakobLichterfeld for tutorial

@all-contributors please add @MathiasSeifert for docu

@all-contributors please add @PhilippDenn for bug
@all-contributors please add @PhilippDenn for ideas

@all-contributors please add @rgrae81 for design
@all-contributors please add @rgrae81 for question

**Comment by JakobLichterfeld** [comment]
Initial version for the bot

@all-contributors please add @TheRealKasumi for bug
@all-contributors please add @TheRealKasumi for code
@all-contributors please add @TheRealKasumi for content
@all-contributors please add @TheRealKasumi for doc
@all-contributors please add @TheRealKasumi for design
@all-contributors please add @TheRealKasumi for example
@all-contributors please add @TheRealKasumi for ideas
@all-contributors please add @TheRealKasumi for infra
@all-contributors please add @TheRealKasumi for maintenance
@all-contributors please add @TheRealKasumi for mentoring
@all-contributors please add @TheRealKasumi for platform
@all-contributors please add @TheRealKasumi for plugin
@all-contributors please add @TheRealKasumi for projectManagement
@all-contributors please add @TheRealKasumi for promotion
@all-contributors please add @TheRealKasumi for question
@all-contributors please add @TheRealKasumi for research
@all-contributors please add @TheRealKasumi for review
@all-contributors please add @TheRealKasumi for security
@all-contributors please add @TheRealKasumi for tool
@all-contributors please add @TheRealKasumi for test
@all-contributors please add @TheRealKasumi for tutorial
@all-contributors please add @TheRealKasumi for video

@all-contributors please add @danielbayerlein for bug
@all-contributors please add @danielbayerlein for code
@all-contributors please add @danielbayerlein for design
@all-contributors please add @danielbayerlein for ideas
@all-contributors please add @danielbayerlein for infra
@all-contributors please add @danielbayerlein for maintenance
@all-contributors please add @danielbayerlein for projectManagement
@all-contributors please add @danielbayerlein for question
@all-contributors please add @danielbayerlein for review
@all-contributors please add @danielbayerlein for translation
@all-contributors please add @danielbayerlein for test

@all-contributors please add @JakobLichterfeld for bug
@all-contributors please add @JakobLichterfeld for code
@all-contributors please add @JakobLichterfeld for doc
@all-contributors please add @JakobLichterfeld for ideas
@all-contributors please add @JakobLichterfeld for infra
@all-contributors please add @JakobLichterfeld for maintenance
@all-contributors please add @JakobLichterfeld for mentoring
@all-contributors please add @JakobLichterfeld for projectManagement
@all-contributors please add @JakobLichterfeld for question
@all-contributors please add @JakobLichterfeld for review
@all-contributors please add @JakobLichterfeld for test
@all-contributors please add @JakobLichterfeld for tutorial

@all-contributors please add @MathiasSeifert for docu

@all-contributors please add @PhilippDenn for bug
@all-contributors please add @PhilippDenn for ideas

@all-contributors please add @rgrae81 for design
@all-contributors please add @rgrae81 for question

**Comment by JakobLichterfeld** [comment]
Initial version for the bot

@all-contributors please add @TheRealKasumi for bug
@all-contributors please add @TheRealKasumi for code
@all-contributors please add @TheRealKasumi for content
@all-contributors please add @TheRealKasumi for doc
@all-contributors please add @TheRealKasumi for design
@all-contributors please add @TheRealKasumi for example
@all-contributors please add @TheRealKasumi for ideas
@all-contributors please add @TheRealKasumi for infra
@all-contributors please add @TheRealKasumi for maintenance
@all-contributors please add @TheRealKasumi for mentoring
@all-contributors please add @TheRealKasumi for platform
@all-contributors please add @TheRealKasumi for plugin
@all-contributors please add @TheRealKasumi for projectManagement
@all-contributors please add @TheRealKasumi for promotion
@all-contributors please add @TheRealKasumi for question
@all-contributors please add @TheRealKasumi for research
@all-contributors please add @TheRealKasumi for review
@all-contributors please add @TheRealKasumi for security
@all-contributors please add @TheRealKasumi for tool
@all-contributors please add @TheRealKasumi for test
@all-contributors please add @TheRealKasumi for tutorial
@all-contributors please add @TheRealKasumi for video

@all-contributors please add @danielbayerlein for bug
@all-contributors please add @danielbayerlein for code
@all-contributors please add @danielbayerlein for design
@all-contributors please add @danielbayerlein for ideas
@all-contributors please add @danielbayerlein for infra
@all-contributors please add @danielbayerlein for maintenance
@all-contributors please add @danielbayerlein for projectManagement
@all-contributors please add @danielbayerlein for question
@all-contributors please add @danielbayerlein for review
@all-contributors please add @danielbayerlein for translation
@all-contributors please add @danielbayerlein for test

@all-contributors please add @JakobLichterfeld for bug
@all-contributors please add @JakobLichterfeld for code
@all-contributors please add @JakobLichterfeld for doc
@all-contributors please add @JakobLichterfeld for ideas
@all-contributors please add @JakobLichterfeld for infra
@all-contributors please add @JakobLichterfeld for maintenance
@all-contributors please add @JakobLichterfeld for mentoring
@all-contributors please add @JakobLichterfeld for projectManagement
@all-contributors please add @JakobLichterfeld for question
@all-contributors please add @JakobLichterfeld for review
@all-contributors please add @JakobLichterfeld for test
@all-contributors please add @JakobLichterfeld for tutorial

@all-contributors please add @MathiasSeifert for docu

@all-contributors please add @PhilippDenn for bug
@all-contributors please add @PhilippDenn for ideas

@all-contributors please add @rgrae81 for design
@all-contributors please add @rgrae81 for question

**Comment by TheRealKasumi** [comment]
Wooow, smart bot. Renamed to file...

**Comment by JakobLichterfeld** [comment]
Initial version, please add what I missed (see the [Emoji Key (Contribution Types Reference)](https://allcontributors.org/docs/en/emoji-key) for a list of valid contribution types.)

@all-contributors please add @TheRealKasumi for bug
@all-contributors please add @TheRealKasumi for code
@all-contributors please add @TheRealKasumi for content
@all-contributors please add @TheRealKasumi for doc
@all-contributors please add @TheRealKasumi for design
@all-contributors please add @TheRealKasumi for example
@all-contributors please add @TheRealKasumi for ideas
@all-contributors please add @TheRealKasumi for infra
@all-contributors please add @TheRealKasumi for maintenance
@all-contributors please add @TheRealKasumi for mentoring
@all-contributors please add @TheRealKasumi for platform
@all-contributors please add @TheRealKasumi for plugin
@all-contributors please add @TheRealKasumi for projectManagement
@all-contributors please add @TheRealKasumi for promotion
@all-contributors please add @TheRealKasumi for question
@all-contributors please add @TheRealKasumi for research
@all-contributors please add @TheRealKasumi for review
@all-contributors please add @TheRealKasumi for security
@all-contributors please add @TheRealKasumi for tool
@all-contributors please add @TheRealKasumi for test
@all-contributors please add @TheRealKasumi for tutorial
@all-contributors please add @TheRealKasumi for video

@all-contributors please add @danielbayerlein for bug
@all-contributors please add @danielbayerlein for code
@all-contributors please add @danielbayerlein for design
@all-contributors please add @danielbayerlein for ideas
@all-contributors please add @danielbayerlein for infra
@all-contributors please add @danielbayerlein for maintenance
@all-contributors please add @danielbayerlein for projectManagement
@all-contributors please add @danielbayerlein for question
@all-contributors please add @danielbayerlein for review
@all-contributors please add @danielbayerlein for translation
@all-contributors please add @danielbayerlein for test

@all-contributors please add @JakobLichterfeld for bug
@all-contributors please add @JakobLichterfeld for code
@all-contributors please add @JakobLichterfeld for doc
@all-contributors please add @JakobLichterfeld for ideas
@all-contributors please add @JakobLichterfeld for infra
@all-contributors please add @JakobLichterfeld for maintenance
@all-contributors please add @JakobLichterfeld for mentoring
@all-contributors please add @JakobLichterfeld for projectManagement
@all-contributors please add @JakobLichterfeld for question
@all-contributors please add @JakobLichterfeld for review
@all-contributors please add @JakobLichterfeld for test
@all-contributors please add @JakobLichterfeld for tutorial

@all-contributors please add @MathiasSeifert for docu

@all-contributors please add @PhilippDenn for bug
@all-contributors please add @PhilippDenn for ideas

@all-contributors please add @rgrae81 for design
@all-contributors please add @rgrae81 for question

**Comment by TheRealKasumi** [comment]
@all-contributors
please add @TheRealKasumi for bug.
please add @TheRealKasumi for code.
please add @TheRealKasumi for content.
please add @TheRealKasumi for doc.
please add @TheRealKasumi for design.
please add @TheRealKasumi for example.
please add @TheRealKasumi for ideas.
please add @TheRealKasumi for infra.
please add @TheRealKasumi for maintenance.
please add @TheRealKasumi for mentoring.
please add @TheRealKasumi for platform.
please add @TheRealKasumi for plugin.
please add @TheRealKasumi for projectManagement.
please add @TheRealKasumi for promotion.
please add @TheRealKasumi for question.
please add @TheRealKasumi for research.
please add @TheRealKasumi for review.
please add @TheRealKasumi for security.
please add @TheRealKasumi for tool.
please add @TheRealKasumi for test.
please add @TheRealKasumi for tutorial.
please add @TheRealKasumi for video.
please add @danielbayerlein for bug.
please add @danielbayerlein for code.
please add @danielbayerlein for design.
please add @danielbayerlein for ideas.
please add @danielbayerlein for infra.
please add @danielbayerlein for maintenance.
please add @danielbayerlein for projectManagement.
please add @danielbayerlein for question.
please add @danielbayerlein for review.
please add @danielbayerlein for translation.
please add @danielbayerlein for test.
please add @JakobLichterfeld for bug.
please add @JakobLichterfeld for code.
please add @JakobLichterfeld for doc.
please add @JakobLichterfeld for ideas.
please add @JakobLichterfeld for infra.
please add @JakobLichterfeld for maintenance.
please add @JakobLichterfeld for mentoring.
please add @JakobLichterfeld for projectManagement.
please add @JakobLichterfeld for question.
please add @JakobLichterfeld for review.
please add @JakobLichterfeld for test.
please add @JakobLichterfeld for tutorial.
please add @MathiasSeifert for docu.
please add @PhilippDenn for bug.
please add @PhilippDenn for ideas.
please add @rgrae81 for design.
please add @rgrae81 for question.

**Comment by TheRealKasumi** [comment]
We should kick that bot into the trash and build our own...

https://github.com/all-contributors
please add @TheRealKasumi for bug.
please add @TheRealKasumi for code.
please add @TheRealKasumi for content.
please add @TheRealKasumi for doc.
please add @TheRealKasumi for design.
please add @TheRealKasumi for example.
please add @TheRealKasumi for ideas.
please add @TheRealKasumi for infra.
please add @TheRealKasumi for maintenance.
please add @TheRealKasumi for mentoring.
please add @TheRealKasumi for platform.
please add @TheRealKasumi for plugin.
please add @TheRealKasumi for projectManagement.
please add @TheRealKasumi for promotion.
please add @TheRealKasumi for question.
please add @TheRealKasumi for research.
please add @TheRealKasumi for review.
please add @TheRealKasumi for security.
please add @TheRealKasumi for tool.
please add @TheRealKasumi for test.
please add @TheRealKasumi for tutorial.
please add @TheRealKasumi for video.
please add @danielbayerlein for bug.
please add @danielbayerlein for code.
please add @danielbayerlein for design.
please add @danielbayerlein for ideas.
please add @danielbayerlein for infra.
please add @danielbayerlein for maintenance.
please add @danielbayerlein for projectManagement.
please add @danielbayerlein for question.
please add @danielbayerlein for review.
please add @danielbayerlein for translation.
please add @danielbayerlein for test.
please add @JakobLichterfeld for bug.
please add @JakobLichterfeld for code.
please add @JakobLichterfeld for doc.
please add @JakobLichterfeld for ideas.
please add @JakobLichterfeld for infra.
please add @JakobLichterfeld for maintenance.
please add @JakobLichterfeld for mentoring.
please add @JakobLichterfeld for projectManagement.
please add @JakobLichterfeld for question.
please add @JakobLichterfeld for review.
please add @JakobLichterfeld for test.
please add @JakobLichterfeld for tutorial.
please add @MathiasSeifert for docu.
please add @PhilippDenn for bug.
please add @PhilippDenn for ideas.
please add @rgrae81 for design.
please add @rgrae81 for question.

**Comment by TheRealKasumi** [comment]
@all-contributors
please add @TheRealKasumi for bug.
please add @TheRealKasumi for code.
please add @TheRealKasumi for content.
please add @TheRealKasumi for doc.
please add @TheRealKasumi for design.
please add @TheRealKasumi for example.
please add @TheRealKasumi for ideas.
please add @TheRealKasumi for infra.
please add @TheRealKasumi for maintenance.
please add @TheRealKasumi for mentoring.
please add @TheRealKasumi for platform.
please add @TheRealKasumi for plugin.
please add @TheRealKasumi for projectManagement.
please add @TheRealKasumi for promotion.
please add @TheRealKasumi for question.
please add @TheRealKasumi for research.
please add @TheRealKasumi for review.
please add @TheRealKasumi for security.
please add @TheRealKasumi for tool.
please add @TheRealKasumi for test.
please add @TheRealKasumi for tutorial.
please add @TheRealKasumi for video.
please add @danielbayerlein for bug.
please add @danielbayerlein for code.
please add @danielbayerlein for design.
please add @danielbayerlein for ideas.
please add @danielbayerlein for infra.
please add @danielbayerlein for maintenance.
please add @danielbayerlein for projectManagement.
please add @danielbayerlein for question.
please add @danielbayerlein for review.
please add @danielbayerlein for translation.
please add @danielbayerlein for test.
please add @JakobLichterfeld for bug.
please add @JakobLichterfeld for code.
please add @JakobLichterfeld for doc.
please add @JakobLichterfeld for ideas.
please add @JakobLichterfeld for infra.
please add @JakobLichterfeld for maintenance.
please add @JakobLichterfeld for mentoring.
please add @JakobLichterfeld for projectManagement.
please add @JakobLichterfeld for question.
please add @JakobLichterfeld for review.
please add @JakobLichterfeld for test.
please add @JakobLichterfeld for tutorial.
please add @MathiasSeifert for docu.
please add @PhilippDenn for bug.
please add @PhilippDenn for ideas.
please add @rgrae81 for design.
please add @rgrae81 for question.

**Comment by TheRealKasumi** [comment]
@all-contributors
please add @TheRealKasumi for bug.
please add @TheRealKasumi for code.
please add @TheRealKasumi for content.
please add @TheRealKasumi for doc.
please add @TheRealKasumi for design.
please add @TheRealKasumi for example.
please add @TheRealKasumi for ideas.
please add @TheRealKasumi for infra.
please add @TheRealKasumi for maintenance.
please add @TheRealKasumi for mentoring.
please add @TheRealKasumi for platform.
please add @TheRealKasumi for plugin.
please add @TheRealKasumi for projectManagement.
please add @TheRealKasumi for promotion.
please add @TheRealKasumi for question.
please add @TheRealKasumi for research.
please add @TheRealKasumi for review.
please add @TheRealKasumi for security.
please add @TheRealKasumi for tool.
please add @TheRealKasumi for test.
please add @TheRealKasumi for tutorial.

**Comment by TheRealKasumi** [comment]
No, I am done! We do it maanually. This is trash!
