### ISSUE TITLE
DevOps: UI: use cache from lint during build

### ISSUE THREAD

**Issue by JakobLichterfeld** [TheRealKasumi/TesLight#137]
During the UI build, the cache from the linting could be reused.

**Comment by danielbayerlein** [comment]
@JakobLichterfeld I think the cache is already in use, or did I miss something?

https://github.com/TheRealKasumi/TesLight/actions/runs/4055643631/jobs/6979063142#step:7:17

**Comment by JakobLichterfeld** [comment]
@danielbayerlein One cache is in use for the linting step and another cache is in use for the build step from what I see. Goal would be to only use one cache for both jobs.

**Comment by danielbayerlein** [comment]
@JakobLichterfeld IMO the cache is reused because the jobs use the same cache key.

**Comment by JakobLichterfeld** [comment]
Imo they do not share the cache, as currently the step_id is used in cache key, which is different for the two jobs. I will debug and adjust if necessary.

**Comment by JakobLichterfeld** [comment]
Cache from Linting is already in use (step_id is not used in cache key but in path key)
Debug see here: https://github.com/TheRealKasumi/TesLight/actions/runs/4091926239/jobs/7056321033
