### ISSUE TITLE
Documentation: How to position the board in the vehicle for correct acceleration directions of the sensor values

### ISSUE THREAD

**Issue by JakobLichterfeld** [TheRealKasumi/TesLight#59]
It would be best if the antenna of the ESP32 points to the front and the USB port to the back of the vehicle. This way we ensure consistent acceleration directions from the sensor for all users.

**Comment by TheRealKasumi** [comment]
Good that you pointed this out again 😋 . I guess otherwise it would get lost in the TFF-Thread at some point.
