### ISSUE TITLE
Documentation: Build: How to get the signal of the factory build footwell lights without any harm

### ISSUE THREAD

**Issue by JakobLichterfeld** [TheRealKasumi/TesLight#62]
Use an "electricity thief" to get the signal of the factory build Footlights. You can even use [this T-connector](https://www.amazon.de/dp/B07F3SGJXR).

It could look like this if you add the correct plugs.
![T-connector](https://user-images.githubusercontent.com/16510328/205510604-9efb6e24-916b-4f64-a53c-3b6531c1ab80.jpg)
![T-connector_2](https://user-images.githubusercontent.com/16510328/205510605-0c2579d4-2ed2-4126-8d09-07ce23598866.jpg)

**Comment by TheRealKasumi** [comment]
Looking very good. I would really like to add this. Where is the extension with the connectors from?

**Comment by JakobLichterfeld** [comment]
Picture ist not mine, I will add part numbers and add it to the part list.

**Comment by JakobLichterfeld** [comment]
The connectors for the LEDs on the Model 3 are these:
A) [Female Connector 35](https://www.mouser.com/ProductDetail/TE-Connectivity-AMP/1534111-1?qs=%2Fha2pyFaduiexECXuMzaAIQHOcZu%252BI25DS0iBamxYRg%3D) (car uses this) - TE Connectivity / AMP P/N: 1534111-1
B) [Male Connector 8](https://www.mouser.com/ProductDetail/571-1-1534155-1) (LED’s use this) - TE Connectivity / AMP P/N: 1-1534155-1
AB) [Retainer / Cover for Connectors 4](https://www.mouser.com/ProductDetail/571-1534027-1) (each connector needs one) - TE Connectivity / AMP P/N: 1534027-1
C) [Pin Connectors 5](https://www.mouser.com/ProductDetail/571-1-928918-1-CT) (2 per plug) - TE Connectivity / AMP P/N: 1-928918-1 (Cut Strip)

Source: [https://teslamotorsclub.com/tmc/posts/3974791/ 16](https://teslamotorsclub.com/tmc/posts/3974791/)
