### ISSUE TITLE
Model: 0.8 mm wall thickness detected

### ISSUE THREAD

**Issue by JakobLichterfeld** [TheRealKasumi/TesLight#72]
In the TesLight_Case and TesLight_Fan_Adapter there are 0.8mm wall thickness detected by jlcpcb.
![image](https://user-images.githubusercontent.com/16510328/209430469-b870edd2-aace-4a1f-86d4-ea15466c299f.png)

**Comment by JakobLichterfeld** [comment]
@rgrae81 can look into this?

**Comment by rgrae81** [comment]
Fan-Adapter has such thin walls but this should be no problem to print.
![grafik](https://user-images.githubusercontent.com/36889990/209432636-938cf4bb-70cd-4fbf-b740-60ead53db535.png)

at the case it should also be related to the fan.
![grafik](https://user-images.githubusercontent.com/36889990/209432702-151bf2f5-9a00-4f54-9ee3-1ed4b311986c.png)

Normally this is not a problem to print. Didn't know tha jlcpcb marks warnings here.

**Comment by JakobLichterfeld** [comment]
Thanks for quick response. I already did ask them to continue the print. If it ran through successful, I will add a short description in build documentation about this.

**Comment by JakobLichterfeld** [comment]
3 D Print in Selective Laser Sintering (SLS) - Nylon from [jlcpcb.com](jlcpcb.com) looks great, no issues found
![Unbenannt](https://user-images.githubusercontent.com/16510328/211290545-fd0952d2-b821-4f0f-8d49-89ed22d4ed4f.jpg)
