### ISSUE TITLE
Lower Fan Temp limit not adjustable below 45 °C

### ISSUE THREAD

**Issue by PhilippDenn** [TheRealKasumi/TesLight#80]
**To Reproduce**
1. Go to Settings
2. Adjust Fan Start Temp to less than 45 °C
3. Apply Settings

**Screenshots**
![image](https://user-images.githubusercontent.com/114821380/209878895-1e83eba2-01d7-4e1e-bf60-edca173f8e54.jpeg)

**Information:**
 - Device: iPad Mini 5
 - Browser Safari

**Comment by JakobLichterfeld** [comment]
https://github.com/TheRealKasumi/TesLight/blob/86004bc481b642a0e2173e348b9d2414062a8ada/mcu/include/configuration/SystemConfiguration.h#L71
