### ISSUE TITLE
"Fan on" button

### ISSUE THREAD

**Issue by PhilippDenn** [TheRealKasumi/TesLight#81]
A simple button for switching the fan on (full power or adjustable) regardless of the temperature

**Comment by JakobLichterfeld** [comment]
Can you add some context about situations where you need it? Is this meant for testing purpose?

**Comment by PhilippDenn** [comment]
To make people happy like my dad who thinks all electronics start burning at 60 degrees 😂

**Comment by danielbayerlein** [comment]
@TheRealKasumi Would it be possible to control this feature via the existing Fan Start Temp setting?

**Comment by TheRealKasumi** [comment]
Should be pretty easy to do. Who ever takes this (probably me), we could rework the fan controller a bit. Maybe introduce an enum `FanMode` with `ALWAYS_OFF`, `ALWAYS_ON` and `AUTO`. This then also needs to be written to the configuration file.

@danielbayerlein Would be possible by setting the starting temp to 0 and the max temp to 1 for example. However I would propose to implement it properly. We could also allow the user to set the fan speed when its always on.
