### ISSUE TITLE
Bug: Stale LEDs when reducing LED count

### ISSUE THREAD

**Issue by MathiasSeifert** [TheRealKasumi/TesLight#98]
**Describe the bug**
When reducing the LED count in the UI below the number of LEDs on the strip, then the "extra" LEDs remain at their last status instead of being turned off.

**To Reproduce**
1. Turn on the light on any zone, make sure all LEDs are lit up
3. Go to 'Advanced' in the zone configuration and reduce the 'LED Count' to a number that is smaller the the actual count of LEDs in that zone.
4. Click 'Apply Settings'
5. Observe that the LEDs above the LED count are still lighting.

**Expected behavior**
When changing the LED Count any LED on the strip that is above the count should be turned off.

**Additional context**
The 'Average Power' that is printed on the console is also affected by this, as it only calculates the power based on the configured LEDs, not the actually lit up LEDs

**Comment by TheRealKasumi** [comment]
This is fixed for the maximum supported number of LED with the new LED driver. See https://github.com/TheRealKasumi/TesLight/pull/141. Problem in theory is still valid for unsupported high numbers of LEDs per zone (>250). But we cant output "off" to an infinite number of LEDs. I guess thats fair.
